allow for main branch as default TCUE-3654
urbanmedia/Publish-Docker-Github-Action pull request #3
Opened 2022-02-16 16:10 UTC by emqMalte

Issue: TCUE-3654

This PR allows for the "default"/prod branch to be "main".

It uses snippet from https://github.com/elgohr/Publish-Docker-Github-Action/commit/b1253b2edfcd8636685eb08955d28698c6db53d2
Minus the test, dunno how to run that.

2022-02-17 16:05 UTC, f-pietsch commented
I am not convinced that this was / is needed, even if the used action is outdated (as everything else, thats maybe the reason that things still work 🤔). Reason: the action should only run based on tags and not on the branch it is pushed to. This works in the other repos by combining the action "create tag" (`urbanmedia/github-tag-action@master`) and the publish action here which triggers upon creation of the tag. The create tag action is still missing in the channelizer repository.

To set the channelizer repo up correctly, have a look at the [semantic repo](https://github.com/urbanmedia/tgs-cue-semantic-service), especially the [create tag workflow](https://github.com/urbanmedia/tgs-cue-semantic-service/blob/develop/.github/workflows/create_tag.yml) where the configuration for the main branch is done.

If the changes also work for the channelizer (which they should but nobody knows), we should close this PR without merging and instead update the action from its original (see this [ticket](https://handelsblatt-gmbh.atlassian.net/browse/TCUE-1768)).

2022-02-17 16:06 UTC, f-pietsch requested changes
Damn, see comment above :)

2022-02-17 16:21 UTC, emqMalte commented
Yeah, everything extremely confusing, I wasn't sure about the tags, but since there seems to be a case where it checks for the tag "master", I assumed it probably should also check for "main".
It might have worked without any changes at all, I didn't even test that 🙈
What I did notice was that it never seemed to get past the `hasCustomTag` step in the if statement.
Though assumed that might be the case in some other scenario 🤷 
Which is why I added the step below that.
All a great mystery to me.

Anway, I created https://github.com/urbanmedia/tgs.channelizer/pull/20 earlier with that `create_tag` action for the 'main' branch and a `merge_main_to_develop` acton as well.
Maybe it just works. 🤷

2022-03-01 10:21 UTC, emqMalte commented
Closing this as everything seems to work so far.

2022-03-01 10:21 UTC, closed without merging